/** Terminal dictionary script; ASCII 9/30 match the raw parser fixtures. */
export const TERMINAL_TABS_SCRIPT = [
  "set tabChar to (ASCII character 9)",
  "set recSep to (ASCII character 30)",
  'tell application "Terminal"',
  '  set out to ""',
  "  repeat with w in windows",
  "    set tabIndex to 0",
  "    repeat with t in tabs of w",
  "      set tabIndex to tabIndex + 1",
  "      try",
  '        set tabTty to ""',
  '        set tabTitle to ""',
  '        set tabScreen to ""',
  "        set tabBusy to false",
  "        try",
  "          set tabTty to tty of t",
  "        end try",
  "        try",
  "          set tabTitle to custom title of t",
  "        end try",
  '        if tabTitle is "" then',
  "          try",
  '            if tabTty is not "" and tabTty is (tty of selected tab of w) then set tabTitle to name of w',
  "          end try",
  "        end if",
  '        if tabTitle is "" then set tabTitle to "Вкладка " & (tabIndex as text)',
  "        try",
  "          set tabScreen to contents of t",
  "        end try",
  "        try",
  "          set tabBusy to busy of t",
  "        end try",
  '        set out to out & (id of w as text) & "-" & (tabIndex as text) & tabChar & tabTitle & tabChar & tabScreen & tabChar & (tabBusy as text) & tabChar & tabTty & recSep',
  "      end try", // Closing a tab must not discard the remaining windows.
  "    end repeat",
  "  end repeat",
  "  return out",
  "end tell",
].join("\n");
