/** Terminal dictionary script; ASCII 9/30 match the raw parser fixtures. */
export const TERMINAL_TABS_SCRIPT = [
  "set tabChar to (ASCII character 9)",
  "set recSep to (ASCII character 30)",
  'tell application "Terminal"',
  '  set out to ""',
  "  repeat with w in windows",
  "    repeat with tabIndex from 1 to (count of tabs of w)",
  "      try",
  "        set t to tab tabIndex of w",
  '        set tabTty to ""',
  '        set tabTitle to ""',
  '        set tabScreen to ""',
  "        set tabBusy to false",
  "        try",
  "          set tabTty to tty of t",
  "        end try",
  "        try",
  "          set tabTitle to custom title of t",
  "        end try",
  '        if tabTitle is "" then',
  "          try",
  '            if tabTty is not "" and tabTty is (tty of selected tab of w) then set tabTitle to name of w',
  "          end try",
  "        end if",
  '        if tabTitle is "" then set tabTitle to "Вкладка " & (tabIndex as text)',
  "        set tabScreen to (contents of tab tabIndex of w) as text",
  "        try",
  "          set tabBusy to busy of t",
  "        end try",
  '        set out to out & (id of w as text) & "-" & (tabIndex as text) & tabChar & tabTitle & tabChar & tabScreen & tabChar & (tabBusy as text) & tabChar & tabTty & recSep',
  "      on error errorText number errorNumber",
  '        set out to out & "__TAB_ERROR__" & tabChar & (id of w as text) & "-" & (tabIndex as text) & tabChar & (errorNumber as text) & ": " & errorText & recSep',
  "      end try", // A failed tab produces diagnostics; other tabs survive.
  "    end repeat",
  "  end repeat",
  "  return out",
  "end tell",
].join("\n");
